In [2]:
import numpy as np

##### 0D tensor/scalar

In [6]:
a = np.array(6)

In [ ]:
a

array(6)

In [ ]:
print("the dimension of a is", a.ndim)

the dimension of a is 0


##### 1D tensor/vector

In [ ]:
a = np.array([1, 2, 3, 4, 5])

In [11]:
a

array([1, 2, 3, 4, 5])

In [12]:
print("the dimension of a is", a.ndim)

the dimension of a is 1


##### 2D tensor/matrix

In [14]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [1, 2, 3, 4, 5]])

In [15]:
a

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [1, 2, 3, 4, 5]])

In [ ]:
print("the dimension of a", a.ndim)

the dimension of a 2


##### 3D tensor

In [17]:
a = np.array([ [ [1, 2], [3, 4] ], [ [5, 6], [6, 7] ] ])

In [19]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [6, 7]]])

In [23]:
print("a is a", a.ndim, "dimensional tensor")

a is a 3 dimensional tensor
